# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09946e26cfa20dc4b26d583df670e42c078c153139c91c5f58351bc07013242b392147da9bc945cfc12c31baeebe03c6496100696c336570bcf793942a00ec9d

test:
  secret_key_base: dce9106361dc638c844fae537f699f2b7059a71b013576533b4381597ecc19529232ab3905c6044315f591c1ed38979cad2378669e8bd6356aedde193de9b97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
